export default {
    login: 'sunilshrees',
    id: 40232752,
    node_id: 'MDQ6VXNlcjQwMjMyNzUy',
    avatar_url: 'https://avatars.githubusercontent.com/u/40232752?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/sunilshrees',
    html_url: 'https://github.com/sunilshrees',
    followers_url: 'https://api.github.com/users/sunilshrees/followers',
    following_url:
        'https://api.github.com/users/sunilshrees/following{/other_user}',
    gists_url: 'https://api.github.com/users/sunilshrees/gists{/gist_id}',
    starred_url:
        'https://api.github.com/users/sunilshrees/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/sunilshrees/subscriptions',
    organizations_url: 'https://api.github.com/users/sunilshrees/orgs',
    repos_url: 'https://api.github.com/users/sunilshrees/repos',
    events_url: 'https://api.github.com/users/sunilshrees/events{/privacy}',
    received_events_url:
        'https://api.github.com/users/sunilshrees/received_events',
    type: 'User',
    site_admin: false,
    name: 'Sunil Shrees',
    company: null,
    blog: '',
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 4,
    public_gists: 0,
    followers: 0,
    following: 1,
    created_at: '2018-06-13T09:28:29Z',
    updated_at: '2022-03-22T12:04:37Z',
};
